webportal/apps/business/course/urls.py
from django.urls import include, path

from apps.business.course import views

specific_urls = [
    path('update/', views.CourseUpdateView.as_view(), name='update'),
    path('detail/', views.CourseDetailView.as_view(), name='detail'),
]

app_name = 'course'
urlpatterns = [
    path('create/', views.CourseCreateView.as_view(), name='create'),
    path('list/', views.CourseListView.as_view(), name='list'),

    path('<int:pk>/', include(specific_urls)),
]

webportal/apps/core/account/urls.py
from django.urls import path

from .views import LoginView, RegisterView, LogoutView

app_name = 'account'
urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('register/', RegisterView.as_view(), name='register'),
    path('logout/', LogoutView.as_view(), name='logout')
]

webportal/apps/core/client/urls.py
from django.urls import path

from .views import RequestView, RequestDoneView

app_name = 'client'
urlpatterns = [
    path('request/', RequestView.as_view(), name='request'),
    path('request/done/', RequestDoneView.as_view(), name='request_done')
]

webportal/apps/core/client/models.py
from django.db import models

from tenant_schemas.models import TenantMixin


class ClientRequest(models.Model):
    full_name = models.CharField(max_length=255)
    short_name = models.CharField(max_length=255)
    preferred_url = models.CharField(max_length=255)

    def __str__(self):
        return self.full_name


class Client(TenantMixin):
    full_name = models.CharField(max_length=255)
    short_name = models.CharField(max_length=255)

    # default true, schema will be automatically created and synced when it is saved
    auto_create_schema = True

    def __str__(self):
        return self.full_name

webportal/apps/core/client/forms.py
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Field, Submit
from django import forms

from .models import ClientRequest


class RequestForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.helper = FormHelper()
        self.helper.layout = self.get_layout()

    @staticmethod
    def get_layout():
        return Layout(
            Field('full_name'),
            Field('short_name'),
            Field('preferred_url'),

            Submit('create', 'Create request')
        )

    class Meta:
        model = ClientRequest
        fields = ['full_name', 'short_name', 'preferred_url']

webportal/apps/core/client/views.py
from django.urls import reverse_lazy
from django.views.generic import CreateView, TemplateView

from apps.core.account.middleware import login_not_required
from .forms import RequestForm


@login_not_required
class RequestView(CreateView):
    template_name = 'client/request.html'
    form_class = RequestForm
    success_url = reverse_lazy('client:request_done')


@login_not_required
class RequestDoneView(TemplateView):
    template_name = 'client/request_done.html'

webportal/templates/client/application/navigation.html
<nav class="navbar navbar-expand-md navbar-dark bg-dark">
  <a class="navbar-brand" href="{% url 'page:home' %}">PROJECT</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample04">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarsExample04">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="coursesDropdown" data-toggle="dropdown">Courses</a>
        <div class="dropdown-menu">
          <a class="dropdown-item" href="{% url 'course:list' %}">Course list</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="{% url 'course:create' %}">Create course</a>
        </div>
      </li>
    </ul>
    <ul class="navbar-nav ml-auto">
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown">
          {{ user.get_full_name }}
        </a>
        <div class="dropdown-menu dropdown-menu-right">
          <a class="dropdown-item" href="#">My account</a>
          <a class="dropdown-item" href="#">Settings</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="{% url 'account:logout' %}">
            <i class="fas fa-sign-out-alt"></i> Logout
          </a>
        </div>
      </li>
    </ul>
  </div>
</nav>