webportal/apps/business/exercise/urls.py
from django.urls import path

from . import views

app_name = 'exercise'
urlpatterns = [
    path('create/', views.ExerciseCreateView.as_view(), name='create'),
    path('<int:pk>/update/', views.ExerciseUpdateView.as_view(), name='update'),
    path('<int:pk>/detail/', views.ExerciseDetailView.as_view(), name='detail'),
    path('<int:pk>/delete/', views.ExerciseDeleteView.as_view(), name='delete'),
    path('<int:pk>/submission_logs/', views.ExerciseSubmissionLogListView.as_view(), name='submission_logs'),
]

webportal/apps/core/client/urls.py
from django.urls import path

from .views import RequestView, RequestDoneView

app_name = 'client'
urlpatterns = [
    path('request/', RequestView.as_view(), name='request'),
    path('request/done/', RequestDoneView.as_view(), name='request_done')
]

webportal/apps/business/exercise/models.py
from django.contrib.contenttypes.fields import GenericRelation
from django.contrib.contenttypes.models import ContentType
from django.db import models
from django.urls import reverse

from apps.business.section.models import SectionItem
from apps.core.account.models import User


class Exercise(models.Model):
    title = models.CharField(max_length=255)
    description = models.TextField()

    code_skeleton = models.TextField()
    public_tests = models.TextField()
    secret_tests = models.TextField()

    objects = models.Manager()

    # For CASCADE functionality for generic foreign key
    section_items = GenericRelation(SectionItem, related_query_name='exercise')

    @property
    def section(self):
        return self.section_items.first().section

    def get_absolute_url(self):
        return reverse('exercise:detail', kwargs={'pk': self.pk})

    def get_update_url(self):
        return reverse('exercise:update', kwargs={'pk': self.pk})

    def get_delete_url(self):
        return reverse('exercise:delete', kwargs={'pk': self.pk})

    def __str__(self):
        return self.title

    class Meta:
        default_permissions = ()


class ExerciseSubmissionLog(models.Model):
    exercise = models.ForeignKey(Exercise, on_delete=models.CASCADE)
    author = models.ForeignKey(User, on_delete=models.CASCADE)

    code = models.TextField()
    tests = models.TextField()

    tests_passed = models.BooleanField(default=False)
    is_final = models.BooleanField(default=False)

    created_at = models.DateTimeField(auto_now_add=True)

    objects = models.Manager()

    class Meta:
        ordering = ['-created_at']
        default_permissions = ()

webportal/apps/business/exercise/forms.py
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Field, Submit, Div
from django import forms

from apps.platform.monaco_editor.widgets import MonacoEditor
from .models import Exercise


class ExerciseCreateForm(forms.ModelForm):
    def __init__(self, lang, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['code_skeleton'].widget = MonacoEditor(language=lang)
        self.fields['public_tests'].widget = MonacoEditor(language=lang)
        self.fields['secret_tests'].widget = MonacoEditor(language=lang)

        self.helper = FormHelper()
        self.helper.layout = self.get_layout()

    @staticmethod
    def get_layout():
        return Layout(
            Field('title'),
            Field('description'),
            Field('code_skeleton'),
            Field('public_tests'),
            Field('secret_tests'),

            Submit('create', 'Create exercise')
        )

    class Meta:
        model = Exercise
        fields = ['title', 'description', 'code_skeleton', 'public_tests', 'secret_tests']


class ExerciseUpdateForm(forms.ModelForm):
    def __init__(self, lang, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['code_skeleton'].widget = MonacoEditor(language=lang)
        self.fields['public_tests'].widget = MonacoEditor(language=lang)
        self.fields['secret_tests'].widget = MonacoEditor(language=lang)

        self.helper = FormHelper()
        self.helper.layout = self.get_layout()

    @staticmethod
    def get_layout():
        return Layout(
            Field('title'),
            Field('description'),
            Field('code_skeleton'),
            Field('public_tests'),
            Field('secret_tests'),

            Submit('update', 'Update exercise')
        )

    class Meta:
        model = Exercise
        fields = ['title', 'description', 'code_skeleton', 'public_tests', 'secret_tests']


class ExerciseSubmissionForm(forms.Form):
    code = forms.CharField(required=False)
    tests = forms.CharField(required=False)
    is_final = forms.BooleanField(required=False)

    def __init__(self, lang, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['code'].widget = MonacoEditor(language=lang)
        self.fields['tests'].widget = MonacoEditor(language=lang)

        self.helper = FormHelper()
        self.helper.layout = self.get_layout()

        self.helper.form_id = 'exerciseSubmissionForm'

    @staticmethod
    def get_layout():
        return Layout(
            Field('code'),
            Field('tests'),
            Div(
                Div(
                    Field('is_final'),
                    css_class='col-2'
                ),
                Div(
                    Submit('submit', 'Submit exercise'),
                    css_class='col'
                ),
                css_class='form-inline form-row'
            )

        )

webportal/apps/business/exercise/views.py
import os

import requests
from django.http import JsonResponse
from django.shortcuts import get_object_or_404
from django.views.generic import CreateView, UpdateView, FormView, DeleteView, ListView
from guardian.mixins import PermissionRequiredMixin

from apps.business.section.models import Section, SectionItem
from apps.core.account.mixins import AnyPermissionRequiredMixin
from . import forms, filters
from .models import Exercise, ExerciseSubmissionLog


class ExerciseCreateView(PermissionRequiredMixin, CreateView):
    permission_required = 'course.manage_course'

    model = Exercise
    form_class = forms.ExerciseCreateForm
    template_name = 'exercise/create.html'

    def dispatch(self, request, *args, **kwargs):
        self.section = get_object_or_404(Section, pk=self.request.GET.get('section_pk'))
        return super().dispatch(request, *args, **kwargs)

    def get_permission_object(self):
        return self.section.course

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs.update({
            'lang': self.section.course.programming_language.editor_name
        })
        return kwargs

    def get_success_url(self):
        return self.section.course.get_absolute_url()

    def form_valid(self, form):
        exercise = form.save()
        SectionItem.objects.create(section=self.section, content_object=exercise)
        return super().form_valid(form)


class ExerciseUpdateView(PermissionRequiredMixin, UpdateView):
    permission_required = 'course.manage_course'

    model = Exercise
    form_class = forms.ExerciseUpdateForm
    template_name = 'exercise/update.html'

    def get_permission_object(self):
        return self.get_object().section.course

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs.update({
            'lang': self.object.section.course.programming_language.editor_name
        })
        return kwargs

    def get_success_url(self):
        return self.object.section.course.get_absolute_url()


class ExerciseDeleteView(PermissionRequiredMixin, DeleteView):
    permission_required = 'course.manage_course'

    model = Exercise
    template_name = 'exercise/delete.html'

    def get_permission_object(self):
        return self.get_object().section.course

    def get_success_url(self):
        return self.object.section.course.get_absolute_url()


class ExerciseDetailView(AnyPermissionRequiredMixin, FormView):
    permission_required = ['course.manage_course', 'course.view_course']

    model = Exercise
    form_class = forms.ExerciseSubmissionForm
    template_name = 'exercise/detail.html'

    def dispatch(self, request, *args, **kwargs):
        self.exercise = get_object_or_404(Exercise, pk=kwargs.get('pk'))
        self.course = self.exercise.section.course
        self.programming_language = self.exercise.section.course.programming_language
        return super().dispatch(request, *args, **kwargs)

    def get_permission_object(self):
        return self.course

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs.update({
            'initial': {
                'code': self.exercise.code_skeleton,
                'tests': self.exercise.public_tests
            },
            'lang': self.programming_language.editor_name
        })
        return kwargs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update({
            'exercise': self.exercise,
            'course': self.course,
            'exercise_submission_logs': self.exercise.exercisesubmissionlog_set.filter(author=self.request.user)
        })
        return context

    def post(self, request, *args, **kwargs):
        form = self.get_form()

        if form.is_valid():
            is_final = form.cleaned_data['is_final']
            user_code = form.cleaned_data['code']
            user_tests = form.cleaned_data['tests']

            exercise_submission_log = ExerciseSubmissionLog(
                exercise=self.exercise,
                author=request.user,
                code=user_code,
                tests=user_tests,
                is_final=is_final
            )

            code_runner_params = {
                'lang': self.programming_language.code_runner_name,
                'code': user_code,
                'tests': self.exercise.secret_tests if is_final else user_tests,
            }

            try:
                code_runner_address = os.environ.get('CODE_RUNNER_ADDRESS')
                r = requests.post(f'{code_runner_address}/executor/execute-tests', data=code_runner_params)
                r_json = r.json()

                result = r_json['output']['result']['convertedResult']

                if result and result['failures'] == 0:
                    exercise_submission_log.tests_passed = True

                exercise_submission_log.save()

                response = {'data': r_json}
            except requests.exceptions.RequestException:
                response = {'data': {'error': 'CODE_RUNNER_CONNECTION_ERROR'}, 'status': 500}

            exercise_submission_log.save()

            return JsonResponse(**response)


class ExerciseSubmissionLogListView(PermissionRequiredMixin, ListView):
    permission_required = 'course.manage_course'

    model = ExerciseSubmissionLog
    context_object_name = 'submission_logs'
    template_name = 'exercise/submission_logs.html'

    def dispatch(self, request, *args, **kwargs):
        self.exercise = get_object_or_404(Exercise, pk=self.kwargs.get('pk'))
        return super().dispatch(request, *args, **kwargs)

    def get_permission_object(self):
        return self.exercise.section.course

    def get_queryset(self, *args, **kwargs):
        qs = super().get_queryset().filter(exercise=self.exercise)
        self.filter = filters.SubmissionLogFilter(self.request.GET, queryset=qs)
        return self.filter.qs

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data()
        context.update({
            'filter': self.filter
        })
        return context

webportal/apps/business/exercise/templates/exercise/create.html
{% extends "client/application.html" %}

{% load crispy_forms_tags %}

{% block content %}<div class="row py-4 text-center text-md-left">
    <div class="col">
      <h2>Create exercise</h2>
    </div>
  </div>

  {% crispy form %}
{% endblock content %}

webportal/apps/business/exercise/templates/exercise/delete.html
{% extends "client/application.html" %}

{% load crispy_forms_tags %}

{% block content %}
  <div class="row py-4 text-center text-md-left">
    <div class="col">
      <h2>Delete exercise</h2>
    </div>
  </div>

  <form method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <input type="submit" class="btn btn-danger" value="Confirm">
  </form>
{% endblock content %}

webportal/apps/business/exercise/templates/exercise/detail.html
{% extends "client/application.html" %}

{% load crispy_forms_tags %}
{% load guardian_tags %}

{% block container_suffix %}-fluid{% endblock %}

{% block content %}
  {% get_obj_perms request.user for course as 'course_perms' %}

  <div class="row my-4">
    <div class="col-12 col-md-4 mb-4">
      <div class="row d-flex justify-content-center mb-3">
        <ul class="nav nav-pills">
          <li class="nav-item">
            <a class="nav-link" data-toggle="pill" href="#extraContainer">Extra</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" data-toggle="pill" href="#assigmentContainer">Assigment</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" data-toggle="pill" href="#outputContainer">Output</a>
          </li>
        </ul>
      </div>

      <div class="row mb-3">
        <div class="col">
          <div class="tab-content">
            <div class="tab-pane" id="extraContainer">
              <div class="card">
                <div class="card-body">
                  <div class="row">
                    <div class="col">
                      <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#versions">
                        <i class="fas fa-history"></i> Versions
                      </button>
                    </div>
                  </div>
                  {% if 'manage_course' in course_perms %}
                    <div class="row mt-2">
                      <div class="col">
                        <a href="{% url 'exercise:submission_logs' pk=exercise.pk %}" class="btn btn-primary">
                          <i class="fas fa-poll"></i> Submission logs
                        </a>
                      </div>
                    </div>
                  {% endif %}
                </div>
              </div>
            </div>

            <div class="tab-pane active" id="assigmentContainer">
              <div class="card">
                <div class="card-body">
                  <h5 class="card-title">{{ exercise.title }}</h5>
                  <p class="card-text">
                    {{ exercise.description | linebreaks }}
                  </p>
                </div>
              </div>
            </div>

            <div class="tab-pane fade" id="outputContainer">
              <div class="card">
                <div class="card-body" id="outputBody">
                  <p class="text-muted mb-0">No tests were runned yet.</p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>

      {#      <div class="tab-content">#}
      {#        <div id="assigment" class="tab-pane fade in show active" role="tabpanel">#}
      {#          <div class="card card-small">#}
      {#            <div class="card-header border-bottom">#}
      {#              <h6 class="m-0">Task assigment</h6>#}
      {#            </div>#}
      {#            <div class="card-body">#}
      {#              {{ exercise.description | linebreaks }}#}
      {#            </div>#}
      {#          </div>#}
      {#        </div>#}
      {#        <div id="output" class="tab-pane fade" role="tabpanel">#}
      {#          <div class="card card-small">#}
      {#            <div class="card-header border-bottom">#}
      {#              <h6 class="m-0">Compiler output</h6>#}
      {#            </div>#}
      {#            <div class="card-body">#}
      {#              <div class="blog-comments__content">#}
      {#                <div class="blog-comments__meta">#}
      {#                  <strong>Stdout</strong>#}
      {#                </div>#}
      {#                <p class="m-0 my-1 mb-2 text-muted" id='stdout'></p>#}
      {#                <div class="blog-comments__meta">#}
      {#                  <strong>Stderr</strong>#}
      {#                </div>#}
      {#                <p class="m-0 my-1 mb-2 text-muted" id='stderr'></p>#}
      {#              </div>#}
      {#            </div>#}
      {#          </div>#}
      {#        </div>#}
      {#      </div>#}
    </div>

    <div class="col-12 col-md-8">
      {% crispy form %}
    </div>
  </div>

  <!-- Modal -->
  <div class="modal fade" id="versions" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Saved versions</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          {% for log in exercise_submission_logs %}
            <button type="button" class="btn btn-{{ log.tests_passed | yesno:'success,secondary' }}">
              {{ log.created_at }}
            </button>
            {% if log.is_final %}<span class="text-success">| final tests |</span>{% endif %}
            {#            <p>{{ log.code | linebreaks }}</p>#}
            {#            <p>{{ log.tests | linebreaks }}</p>#}
            {#            <p>is final: {{ log.is_final }}</p>#}
            {#            <p>tests passed: {{ log.tests_passed }}</p>#}
            <hr>
          {% endfor %}
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <button type="button" class="btn btn-primary">Save changes</button>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

{% block scripts %}
  {{ block.super }}

  <script>

    function nltoBr (string) {
      return string.replace('\n', '<br />', 'g')
    }

    function convertTestCase (testCase) {
      const el = $('<div></div>')

      const header = $('<div></div>')
      header.append(testCase.name)

      const body = $('<div></div>')
      body.css('margin-left', '10px')

      if (testCase.failure) {
        body.append(`<p style="color: red">Failure: ${nltoBr(testCase.failure)}</p>`)
      } else {
        body.append(`<p style="color: green">Passed</p>`)
      }

      if (testCase.output) {
        body.append(`<p style="color: gray">Output: ${nltoBr(testCase.output)}</p>`)
      }

      el.append(header, body)

      return el
    }

    function convertTestSuite (testSuite) {
      const el = $('<div></div>')

      const header = $('<div></div>')
      header.append(testSuite.name)

      const body = $('<div></div>')
      body.css('margin-left', '10px')

      testSuite.testCases.forEach(testSuiteNested => {
        body.append(convertTestCase(testSuiteNested))
      })

      el.append(header, body)

      return el
    }

    $('#exerciseSubmissionForm').on('submit', function (event) {
      event.preventDefault()

      $.post($(this).attr('action') || window.location.href, $(this).serialize(), function (data) {
        console.log(data)
        const output = data.output

        const { result: { convertedResult } } = data.output

        if (convertedResult && convertedResult.failures === 0) {
          if (convertedResult.testCases.length > 0) {

          }

          alert('Great, all tests have passed')
        } else {
          alert('Failed, see output tab')
        }

        const resEl = $('<div></div>')
        resEl.css('font-size', '0.75em')

        if (convertedResult) {
          if (convertedResult.failures === 0) {
            resEl.append(`<p style="color: green">All tests have passed</p>`)
          } else {
            resEl.append(`<p style="color: red">Failures: ${convertedResult.failures}</p>`)
          }

          convertedResult.testSuites.forEach(testSuite => {
            resEl.append(convertTestSuite(testSuite))
          })
        }

        if (output.error) {
          resEl.append(`<p style="color:red">Error: ${nltoBr(output.error)}</p>`)
        }

        if (output.stderr) {
          resEl.append(`<p style="color:red">Stderr: ${nltoBr(output.stderr)}</p>`)
        }

        if (output.stdout) {
          resEl.append(`<hr><p style="color:gray">Stdout: ${nltoBr(output.stdout)}</p>`)
        }

        $('#outputBody').html(resEl)

      }).fail(function (jqXHR, textStatus, errorThrown) {
        alert(jqXHR.responseJSON.error)
      })
    })
  </script>
{% endblock %}

webportal/apps/business/exercise/templates/exercise/submission_logs.html
{% extends "client/application.html" %}

{% load crispy_forms_tags %}

{% block content %}
  <div class="row">
    <div class="col-md-3 mb-4">
      {% crispy filter.form %}
    </div>
    <div class="col-md-9">
      <div class="table-responsive">
        <table class="table">
          <thead>
          <tr>
            <th scope="col">id</th>
            <th scope="col">Author</th>
            <th scope="col">Tests passed</th>
            <th scope="col">Submitted at</th>
          </tr>
          </thead>
          <tbody>
          {% for log in submission_logs %}
            <tr>
              <td>{{ log.pk }}</td>
              <td>{{ log.author }}</td>
              <td>
                {% if log.tests_passed %}
                  Yes
                {% else %}
                  No
                {% endif %}
              </td>
              <td>{{ log.created_at }}</td>
            </tr>
          {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  </div>
{% endblock content %}

webportal/apps/business/exercise/templates/exercise/update.html
{% extends "client/application.html" %}

{% load crispy_forms_tags %}

{% block content %}
  <div class="row py-4 text-center text-md-left">
    <div class="col">
      <h2>Update exercise</h2>
    </div>
  </div>

  {% crispy form %}
{% endblock content %}